### ISSUE TITLE
Compatibility for Android 13 alarm restrictions

### ISSUE THREAD

**Issue by ishaangarg** [gojek/courier-android#25]
Thanks for this much needed android library now that paho project is abandoned.

With Android 13, setExactAndAllowWhileIdle() permission is now protected permission & only alarm apps can use it.

Can the connection with broker reliably survive in background without this permission? What are your plans to target Android 13 compatibility.

TIA

**Comment by deepanshu42** [comment]
Hi @ishaangarg. Yes, you are right. Starting Android 12, scheduling an exact alarm requires applications to obtain [SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM) permission.

As an alternative, Courier library provides an implementation of ping sender which uses WorkManager. WorkManager allows you to reliably schedule ping requests, to maintain the connection with broker. You can more about it [here](https://gojek.github.io/courier-android/docs/PingSender#workmanagerpingsender).
Thank you.
