### ISSUE TITLE
Retry Policy doesn't work on Authentication failures.

### ISSUE THREAD

**Issue by satyarajrapido** [gojek/courier-android#74]
@deepanshu42 

The connection retry's continuously for every 1 second indefinitely when there is an authentication failure. 

Even after the retry policies set and and also using default retry policy doesn't not exponentially retry the connection. 

After setting the authFailureHandler = AuthenticatorHandler() when creating MqttV3Configuration, this will help not retry more than once.

But want to know if that's an expected behaviour to retry every 1 second indefinitely.

**Comment by deepanshu42** [comment]
HI @satyarajrapido, we have recently added the capability of customising the retry behaviour for authentication failures in [v0.2.7](https://github.com/gojek/courier-android/releases/tag/0.2.7). You can achieve this by setting connect retry policy inside `MqttV3Configuration`.

**Comment by satyarajrapido** [comment]
@deepanshu42 I have tried it on v0.2.7 too, it's the similar issue, also on AuthFailure, the reconnect time is set to zero on code in v0.2.7.

Is it expected to return zero in case of auth failure? 

![code](https://github.com/gojek/courier-android/assets/48671072/3d5000ce-12d3-4089-83a9-4000f6c2f774)

**Comment by deepanshu42** [comment]
@satyarajrapido This is the default behaviour to immediately retry on auth failures. As mentioned in [previous message](https://github.com/gojek/courier-android/issues/74#issuecomment-1661987510), you can customise this by creating your own connect retry policy.
