### ISSUE TITLE
How to Set will in MQTT?

### ISSUE THREAD

**Issue by ak-peerbits** [gojek/courier-android#85]
Hello,

I'm currently using the courier library in my Android project for MQTT communication. However, I am facing difficulty in figuring out how to set the will message in MQTT. The Last Will and Testament (LWT) message is crucial for ensuring that a disconnect is properly handled, and I'd like to understand how to configure this using your library.

### **Steps to Reproduce**
Integrated the courier library into my project following the [official documentation](https://gojek.github.io/courier-android/docs/MqttConfiguration).
Established a connection to the MQTT broker using the library.
Now, I'm looking to set up the will message but couldn't find relevant information in the documentation.

### **Expected Behavior**
There should be a clear method or a way to set the will message in the MQTT connection options provided by courier.

### **Actual Behavior**
Currently, there seems to be no straightforward way or documentation on how to set the will message when using this library.

### **Environment Details**

- Library Version: [courier-0.2.9]
- Android Version: [ Android 14]
- Development Environment: [Android Studio Jellyfish | 2023.3.1 on macOS Sonoma]

### **Additional Context**
It would be helpful if you could provide a code snippet or a guide on how to implement the will message in the MQTT connection using courier. If this feature isn't supported, could you consider adding it in a future release?

### **Code Snippet**
<img width="712" alt="Screenshot 2024-08-29 at 1 32 05 PM" src="https://github.com/user-attachments/assets/7aafb428-4c07-4e41-b24d-029365fd8944">

Thank you for your assistance!

**Comment by deepanshu42** [comment]
This feature is not available in [0.3.1](https://github.com/gojek/courier-android/releases/tag/0.3.1) release
